### PR TITLE
Note Cloud Foundry as well!

### PR DESCRIPTION
**Pull request by mogul**
CF is the original home of the OSBAPI! This will make it clearer that people can also use this with Pivotal Cloud Foundry, BlueMix, cloud.gov, etc.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mogul** [comment]
Hm, I was going by the content of [this blog post describing the broker](https://aws.amazon.com/blogs/opensource/provision-aws-services-kubernetes-aws-service-broker/):

> Today, I would like to introduce you to the AWS Service Broker, an implementation of the OSB API that will allow you to provision AWS services like RDS and EMR directly through any platform supporting the OSB API. Currently, that list includes Kubernetes, OpenShift, and Cloud Foundry.

I guess what is meant there is that you have to run it on k8s, but after that the OSB API it exposes can then be used by any of k8s, OpenShift, and CF. 

Why does the broker have a dependency on running in k8s, rather than being an environment-agnostic container people can run anywhere? Other than the installation instructions, what is k8s-specific about the broker's code?

How can I follow progress on the new broker that's in the works?

**Comment by mogul** [comment]
Hi @jaymccon, any breadcrumbs for me here?
> Why does the broker have a dependency on running in k8s, rather than being an environment-agnostic container people can run anywhere? Other than the installation instructions, what is k8s-specific about the broker's code?
> 
> How can I follow progress on the new broker that's in the works?

**Comment by jaymccon** [comment]
@mogul the upstream broker uses kubernetes api's to launch worker pods that actually perform the osb operations.

There are no resources on the new broker at this time, but we plan to open the beta up publicly (into this repo) in the coming weeks. Keep an eye out for big updates here.

**Comment by jaymccon** [comment]
closing unmerged, the update due to be added tomorrow includes documentation for cloud foundry

**Pull request closed without merging**
