### PR TITLE
Support IAM Roles for Service Accounts [Web Identity Roles]

### PR DESCRIPTION
**Pull request by enieuw**
## Overview

This PR bumps the version of the AWS GO SDK to 1.23.2 (First version that supports the WebIdentityRoleProvider) in order to be able to support using EKS Service Account tokens to assume IAM roles. 

## Testing Instructions

* Spin up an EKS cluster with Service Broker
* Follow these instructions to get IAM roles for Service accounts working: https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
* Annotate the ServiceAccount of the service broker with the correct IAM role
* Block the service broker from using the instance profile following these instructions https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html
* Restart the service broker pod. 

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sd0408** [comment]
Does this fix remove the need for an AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY when deploying the Service Broker, or is this for the assume role functionality?

**Comment by enieuw** [comment]
> Does this fix remove the need for an AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY when deploying the Service Broker, or is this for the assume role functionality?

If you use the functionality in EKS that allows you to assign IAM roles to Service Accounts then yes. This will allow you to assign the ServiceBroker IAM role to the SA associated with the ServiceBroker pod and with this PR all permissions will be automatically picked up then provided you've block access to the metadata service so it will not use the instance profile.

**Comment by miguelaferreira** [comment]
@jaymccon any chance you will be able to look at this issue? It's currently blocking my team.

**Comment by sd0408** [comment]
@jaymccon, is there any plan to move forward with this change? This is blocking us as well.

**Comment by enieuw** [comment]
@jaymccon What do we need to get this merged? This MR has been open for six months now

**Comment by asychev** [comment]
Is this project alive or not?..

**Comment by carbohydrates** [comment]
any update on this MR?

**Comment by kferrone** [comment]
Merge please?

**Pull request merged**
